"""first migrations

Revision ID: e12eec8b65f4
Revises: 
Create Date: 2024-03-02 03:33:45.604766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e12eec8b65f4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drivers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('profile_pic', sa.String(length=40), nullable=True),
    sa.Column('bio', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('available', 'unavailable', 'in_transit', 'on_pickup', 'matched', 'arrived', name='driver_status'), server_default='unavailable', nullable=True),
    sa.Column('date', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('rides',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('driver_id', sa.String(length=36), nullable=True),
    sa.Column('destination', sa.ARRAY(sa.Float()), nullable=False),
    sa.Column('pickup_location', sa.ARRAY(sa.Float()), nullable=False),
    sa.Column('fare', sa.Float(), server_default='0.0', nullable=True),
    sa.Column('status', sa.Enum('completed', 'in_transit', 'canceled', 'confirmed', 'arrived', name='ride_status'), nullable=False),
    sa.Column('paid', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('date', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rides')
    op.drop_table('drivers')
    # ### end Alembic commands ###
